# codecov.yml
coverage:
  status:
    patch:
      default:
        target: 80%
        only_pulls: true
        informational: false
    project:
      ganit-core:
        target: 80%
        paths:
          - crates/core/
